
    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.01:3306/db_hospital
        username: root
        password: 123456

      #日期格式化
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

      thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
      mvc:
        async:
          #设置超时时间
          request-timeout: 20000

    mybatis:
      mapper-locations: classpath:mapper/*.xml
    server:
      port: 8088
    #pageHelper配置（官网推荐配置）
    pagehelper:
      helper-dialect: mysql
      reasonable: true
      support-methods-arguments: true
      params: count=countSql

    # 头像保存路径
    windowsFilePath: D:/ct_sys/userPic/
    linuxFilePath: /root/ct_sys/userPic/
